export const MAKE_REQUEST = 'MAKE_REQUEST'
export const FAIL_REQUEST = 'FAIL_REQUEST'
export const GET_LIST = 'GET_LIST'
export const DELETE_LIST = 'DELETE_LIST'
export const CREATE_LIST = 'CREATE_LIST'
export const UPDATE_LIST = 'UPDATE_LIST'
export const OBJECT_LIST = 'OBJECT_LIST'
